version: '3.9'

services:
  server:
    build: .
    ports:
      - "3000:4000"
  db:
    image: 'mysql:5.7'
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: 'scott0929'
      MYSQL_ROOT_PASSWORD: 'parkjusung12'
    command: npm run dev
