version: '3.9'

services:
  server:
    image: 'scott0929/receipeapp'
    ports:
      - "3000:8080"
    depends_on:
      - db
    restart: on-failure
  db: 
    image: 'postgres' # Change the image to use PostgreSQL
    ports:
      - '4444:5432'  # PostgreSQL default port
    environment:
      POSTGRES_USER: 'postgres'  # PostgreSQL default superuser
      POSTGRES_PASSWORD: 'root'

