version: '3.9'

services:
  server:
    build: .
    ports:
      - "8081:8080"
  db: 
    image: 'postgres' # Change the image to use PostgreSQL
    ports:
      - '4444:5432'  # PostgreSQL default port
    environment:
      POSTGRES_USER: 'postgres'  # PostgreSQL default superuser
      POSTGRES_PASSWORD: 'root'

